import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Analytics } from '@vercel/analytics/next';
import { SmoothCursor } from "@/components/ui/smooth-cursor";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ayyub",
  description: "Generated by create next app",
  openGraph: {
    title: "Ayyub",
    description: "Generated by create next app",
    images: [
      {
        url: '/og-image.png', // Place your image in the public folder
        width: 1200,
        height: 630,
        alt: 'Ayyub - Description of your image',
      },
    ],
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: "Ayyub",
    description: "Generated by create next app",
    images: ['/og-img.png'],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
        attribute='class'
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
          {children}
          <Analytics />

        </ThemeProvider>
      </body>
    </html>
  );
}
